import type { Metadata } from "next";
import AuthProvider from "@/providers/auth";
import { AxiosProvider } from "@/providers/axios";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AxiosProvider>{children}</AxiosProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
