root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server cmd/server/*.go"
  bin = "./tmp/server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", ".git", "web"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]
  follow_symlink = false
  kill_delay = "0s"
  poll=true

[log]
  time = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"