services:
  server:
    build: .
    container_name: ff-server
    restart: always
    ports:
      - "8090:8195"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: ff_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword123
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  db-data:

networks:
  backend:
    driver: bridge
