import type { Metadata } from "next";
import "@/app/globals.css";
import AuthProvider from "@/providers/auth";
import { AxiosProvider } from "@/providers/axios";
import Header from "@/components/header";
import SideBar from "@/components/sidebar";
import { ActiveProjectProvider } from "@/providers/project";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AxiosProvider>
            <ActiveProjectProvider>
              <Header />
              <div className="layout">
                <SideBar />
                <div className="main-content">{children}</div>
              </div>
            </ActiveProjectProvider>
          </AxiosProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
